chat/urls.py
from django.urls import path

from .views import index, RoomDetail, ChatListView

urlpatterns = [
    path('', index, name='index'),
    path('messages/', ChatListView.as_view(), name='messages'),
    path('<str:room_name>/', RoomDetail.as_view(), name='room'),
]

websockets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Chat(models.Model):
    users = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)



class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

myapp/models.py
from django.db import models

# Create your models here.

chat/views.py
from django.contrib.auth.models import User
from django.db.models import Q
from django.views.generic import DetailView, ListView
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json

from .models import Chat


def index(request):
    return render(request, 'chat/index.html', {})

print(User.objects.all())
# print(Chat.objects.first().users.all())
class RoomDetail(DetailView):
    def get(self, *args, **kwargs):
        user = User.objects.get(username=kwargs['room_name'])
        chat = Chat.objects.filter(users__in=[user.id, self.request.user.id]).first()
        if not chat:
            chat = Chat.objects.create()
            chat.users.add(self.request.user.id)
            chat.users.add(user.id)
        return render(self.request, 'chat/room.html', {
            'room_name_json': mark_safe(json.dumps(kwargs['room_name'])),
            'chat': chat
        })


class ChatListView(ListView):
    model = User
    template_name = 'chat/messages_list.html'

    def get_queryset(self):
        return User.objects.exclude(pk=self.request.user.pk)

myapp/views.py
from django.shortcuts import render

# Create your views here.

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/messages_list.html
{% for user in object_list %}
<a href="{% url 'room' user %}">{{ user }}</a>
{% endfor %}

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
{% for message in chat.message_set.all %}
{{ message }}
<br>
{% endfor %}
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>